### ISSUE TITLE
web书架添加布局设置

### ISSUE THREAD

**Issue by Xwite** [gedoor/legado#3069]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

阅读页面支持字间距 行距(基础为1em) 段距

### 期望实现方式 / How to implement

> vue3
```css
p {
  letter-spacing: calc(v-bind("letterSpacing") * 1em);
  line-height: calc(1 + v-bind("lineSpacing"));
  margin: calc(v-bind("paragraphSpacing") * 1em) 0;
}
```
